# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: words
  appname: words-api
  image: dockersamples/k8s-wordsmith-api
  port: 8080
  sourcePort: 8080
  clusterIP: None
  replicas: 2