# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: web
  appname: words-web
  image: dockersamples/k8s-wordsmith-web
  port: 80
  sourcePort: 8081
  type: LoadBalancer