# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: db
  appname: words-db
  image: dockersamples/k8s-wordsmith-db
  port: 5432
  sourcePort: 5432
  clusterIP: None